### PR TITLE
[HT-1941] fix signature of create/put methods to Attribute class

### LINKED ISSUE #24: hasty.attribute.Attribute.edit() - Project ID is None + Optional parameters required
When trying to use the function to edit an attribute I ran into two issues.

**Issues:**
1. The two optional arguments `description` and `norder` are actually required
`TypeError: edit() missing 2 required positional arguments: 'description' and 'norder'`

2. Running the function will give you an error 500 due to the project id being `None`
`requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.hasty.ai/v1/projects/None/attributes/9883afc3-2a5d-44b5-abd0-c83e7f37bc40`

**Solutions:**
1. Use `Optional` from typing to make the two parameters optional:
`description: Optional[str] = None, norder: Optional[float] = None`
You could also do in two other ways: `description: str = None` or even `description: Union[str, None]`
It comes down to just a preference at the end, just think the Optional makes the code clear. :)
It would be good to apply this everywhere anything is optional as I noticed the issue in other functions in the API.
More than happy to submit a pull request if you'd like.

2. My quick fix was to add the project id as a required argument, but this is just a temporary workaround.
You would need to look into this as this issue might be present in other functions in the API.

### PR DESCRIPTION
**Pull request by tumani1**
- fixed signature of create/put methods to Attribute class

closes #24

### CODE REVIEW

**Comment by xeviknal** [comment]
@DevGlitch here we have PR for your issue? What do you say?

**Comment by xeviknal** [comment]
@tumani1 do we need to update any documentation for this change?

**Comment by DevGlitch** [comment]
> @DevGlitch here we have PR for your issue? What do you say?

@xeviknal looks like it is fixing the optional argument issue. However, unsure if this fixes the error 500 due to the project id being None.

**Comment by tumani1** [comment]
> > @DevGlitch here we have PR for your issue? What do you say?
> 
> @xeviknal looks like it is fixing the optional argument issue. However, unsure if this fixes the error 500 due to the project id being None.

project_id - it is a mandatory parameter and the user can set `project_id` when he inits object.
for example:
```
client = get_client()
instance = Attribute(requester, res, {"project_id": "project_id:, "atribute_id": "atribute_id"})
```

**Comment by DevGlitch** [comment]
> project_id - it is a mandatory parameter and the user can set `project_id` when he inits object.
> 
> For example:
> 
> ```
> client = get_client()
> instance = Attribute(client, {"project_id": "project_id", "atribute_id": "atribute_id"})
> ```

Yes, that's right, but whenever we try using this function it gives us that error 500, and the project ID is showing as None in the request URL.

For example, we get the attribute through the `Hasty.Project` and get the single attribute and try editing it:

```python
h = Client(api_key)
project = h.get_project(project_id)

# Getting all attributes of the project
hasty_attributes = project.get_attributes()

# Selecting the first attribute just as an example
selected_attribute = hasty_attributes[0]

# It gives us this attribute class:
>> Attribute(id="9b04862a-483a-4678-987a-8ab182fa655c", name="species", attribute_type="SELECTION", description=None, norder=2, values=[{'id': 'f03e27f8-8322-4df7-b07c-80292100e08d', 'value': 'Leopard: African'}])

# Trying to edit the attribute with the new/updated values
selected_attribute.edit(name="species", attribute_type="SELECTION", values=["Leopard: African", "Lion: African"])

# Gives us this error:
>> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.hasty.ai/v1/projects/None/attributes/9b04862a-483a-4678-987a-8ab182fa655c
```

As you can see the URL doesn't have the project id and has `None` instead.

Not sure if I'm doing something wrong, but I don't have this type of issue with other functions which led me to believe it is an issue in the API. Please advise.

**Comment by tumani1** [comment]
> > project_id - it is a mandatory parameter and the user can set `project_id` when he inits object.
> > For example:
> > ```
> > client = get_client()
> > instance = Attribute(client, {"project_id": "project_id", "atribute_id": "atribute_id"})
> > ```
> 
> Yes, that's right, but whenever we try using this function it gives us that error 500, and the project ID is showing as None in the request URL.
> 
> For example, we get the attribute through the `Hasty.Project` and get the single attribute and try editing it:
> 
> ```python
> h = Client(api_key)
> project = h.get_project(project_id)
> 
> # Getting all attributes of the project
> hasty_attributes = project.get_attributes()
> 
> # Selecting the first attribute just as an example
> selected_attribute = hasty_attributes[0]
> 
> # It gives us this attribute class:
> >> Attribute(id="9b04862a-483a-4678-987a-8ab182fa655c", name="species", attribute_type="SELECTION", description=None, norder=2, values=[{'id': 'f03e27f8-8322-4df7-b07c-80292100e08d', 'value': 'Leopard: African'}])
> 
> # Trying to edit the attribute with the new/updated values
> selected_attribute.edit(name="species", attribute_type="SELECTION", values=["Leopard: African", "Lion: African"])
> 
> # Gives us this error:
> >> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.hasty.ai/v1/projects/None/attributes/9b04862a-483a-4678-987a-8ab182fa655c
> ```
> 
> As you can see the URL doesn't have the project id and has `None` instead.
> 
> Not sure if I'm doing something wrong, but I don't have this type of issue with other functions which led me to believe it is an issue in the API. Please advise.
> 
> Also, if you try doing this on a `LabelClass` which is basically the same kind of `edit()` function. We don't have any errors and it edits properly.

I got you. Fixed

**Comment by DevGlitch** [comment]
> I got you. Fixed

Thank you!

**Review by xeviknal — APPROVED** [review]
GLMT!

**Pull request merged**
